CREATE TABLE users (
	id INTEGER NOT NULL, 
	username VARCHAR(64) NOT NULL, 
	email VARCHAR(120) NOT NULL, 
	profile VARCHAR(20) NOT NULL, 
	password VARCHAR(64) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (username), 
	UNIQUE (email)
);
INSERT INTO users VALUES(1,'Amer Ahmed','Ahmed.mahamoud345@gmail.com','2525482b341bdfb5.png','$2b$12$leuLLKBETDd7f//ORfc0yuxLJlDYeCnJHeo7Tlvry649frOgbu40i');
INSERT INTO users VALUES(2,'Amir Ramic','amir_ramic@msn.com','20d5a0ccada01efc.jpeg','$2b$12$7mVwEiR1nbADJ4Uv0Q7UVe08ESLUxPpdnKPRm6g.SZcZttLgSx82a');
CREATE TABLE posts (
	id INTEGER NOT NULL, 
	title VARCHAR(100) NOT NULL, 
	published DATETIME NOT NULL, 
	content TEXT NOT NULL, 
	user_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);
INSERT INTO posts VALUES(4,'List of PyCon 2022 Talks','2022-02-03 12:49:32.413255','Has ea verear adolescens, elit justo constituam duo in, vix an copiosae contentiones. Eos persius consequuntur no, esse percipit cum ea, per modus harum praesent at. Et clita delenit luptatum usu? No cum interpretaris concludaturque. Congue pertinax ea mea. nBrute iracundia philosophia ei quo, nam at adhuc idque, ex dolor homero mei. No mea affert tacimates pertinacia, in maluisset dissentias consectetuer mei, vel no aliquam splendide. In has nobis vocent adipisci? Pri clita delicata in, iusto viris scripserit vim in? Sit in lorem complectitur. Sanctus eloquentiam eum ut, et sumo apeirian mea? Vim te affert populo voluptaria, utinam consul ad duo!',1);
INSERT INTO posts VALUES(5,'List of PyCon 2022 Talks','2022-02-03 12:51:29.553682','Has ea verear adolescens, elit justo constituam duo in, vix an copiosae contentiones. Eos persius consequuntur no, esse percipit cum ea, per modus harum praesent at. Et clita delenit luptatum usu? No cum interpretaris concludaturque. Congue pertinax ea mea. nBrute iracundia philosophia ei quo, nam at adhuc idque, ex dolor homero mei. No mea affert tacimates pertinacia, in maluisset dissentias consectetuer mei, vel no aliquam splendide. In has nobis vocent adipisci? Pri clita delicata in, iusto viris scripserit vim in? Sit in lorem complectitur. Sanctus eloquentiam eum ut, et sumo apeirian mea? Vim te affert populo voluptaria, utinam consul ad duo.',1);
INSERT INTO posts VALUES(6,'Record My Videos','2022-02-03 12:52:23.086481',replace(replace('Ad vel possim delicatissimi, delectus detraxit per cu. Ad pri vidit modus altera! In erat complectitur sit, quo no nostro insolens? Aliquam patrioque scribentur quo ad, partem commune eos at. Eius vivendo comprehensam has ne, sea ne eros mazim oratio. Soluta populo te duo, ne pro causae fabulas percipitur, feugiat.\r\n','\r',char(13)),'\n',char(10)),1);
INSERT INTO posts VALUES(7,'Workplace Boosts Productivit','2022-02-03 12:53:00.322428',replace(replace('Has ea verear adolescens, elit justo constituam duo in, vix an copiosae contentiones. Eos persius consequuntur no, esse percipit cum ea, per modus harum praesent at. Et clita delenit luptatum usu? No cum interpretaris concludaturque. Congue pertinax ea mea.nBrute iracundia philosophia ei quo, nam at adhuc idque, ex dolor homero mei. No mea affert tacimates pertinacia, in maluisset dissentias consectetuer mei, vel no aliquam splendide. In has nobis vocent adipisci? Pri clita delicata in, iusto viris scripserit vim in? Sit in lorem complectitur. Sanctus eloquentiam eum ut, et sumo apeirian mea? Vim te affert populo voluptaria, utinam consul ad duo.\r\n','\r',char(13)),'\n',char(10)),1);
INSERT INTO posts VALUES(8,'Best Python IDE','2022-02-03 12:53:45.906604','Elit contentiones nam no, sea ut consul adipiscing. Etiam velit ei usu, sonet clita nonumy eu eum. Usu ea utroque facilisi, cu mel fugit tantas legimus, te vix quem nominavi. Prima deserunt evertitur ne qui, nam reprimique appellantur ne.',1);
INSERT INTO posts VALUES(9,'Improve Your Programming','2022-02-03 12:54:32.019579','Sanctus senserit vis id, ut eum iuvaret invidunt constituam? Nonumes facilis mei an, ad elit explicari persequeris pri, dico recusabo quo id? At mea lorem repudiandae. Sed causae sensibus forensibus ea, ne ornatus suscipiantur consectetuer mel, affert nostro nominati cu qui. Te sanctus constituto est, corrumpit pertinacia eos et, mei libris persequeris an.nQuo fuisset sensibus in. Ad est assueverit adversarium, viris aperiri numquam est ad. Pro mediocrem iudicabit ei! Cu aperiam diceret sit.',1);
INSERT INTO posts VALUES(10,'Top 5 Programming Lanaguage','2022-02-03 12:55:06.534706','Te melius apeirian postulant cum, labitur admodum cu eos! Tollit equidem constituto ut has. Et per ponderum sadipscing, eu vero dolores recusabo nec! Eum quas epicuri at, eam albucius phaedrum ad, no eum probo fierent singulis. Dicat corrumpit definiebas id usu, in facete scripserit eam.Vim ei exerci nusquam. Agam detraxit an quo? Quo et partem bonorum sensibus, mutat minimum est ad. In paulo essent signiferumque his, quaestio sadipscing theophrastus ad has. Ancillae appareat qualisque ei has, usu ne assum zril disputationi, sed at gloriatur persequeris',1);
INSERT INTO posts VALUES(11,' Sublime Text Tips and Tricks','2022-02-03 12:55:39.426033','Ea vix dico modus voluptatibus, mel iudico suavitate iracundia eu. Tincidunt voluptatibus pro eu? Nulla omittam eligendi his ne, suas putant ut pri. Ullum repudiare at duo, ut cum habeo minim laudem, dicit libris antiopam has ut! Ex movet feugait mea, eu vim impetus nostrud cotidieque. nEi suas similique quo, his simul viris congue ex? Graeci possit in est, ne qui minim delectus invenire. Mei ad error homero maluisset, tacimates assentior per in, vix ut vocent accusata! Mei eu inermis pericula patrioque? Debet denique sea at, ad cibo reformidans theophrastus per, cu inermis maiestatis vim! nUt odio feugiat voluptua est, euismod volutpat qualisque at sit, has ex dicit ornatus inimicus! Eu ferri laoreet vel, dicat corrumpit dissentias nec in. Illum dissentiunt eam ei, praesent voluptatum pri in? Ius in inani petentium, hinc elitr vivendum an vis, in vero dolores electram ius?',1);
INSERT INTO posts VALUES(12,' The Best Programming Podcasts','2022-02-03 12:57:38.418193','Vidisse malorum platonem vel no. Persecuti adversarium ut sit, quo et stet velit mundi! Id per homero expetenda. Est brute adipisci et! nLorem aliquip has in, quo debet ceteros sadipscing ne! An sea odio ornatus inermis, an per ipsum persecuti dissentiunt, no mea bonorum pertinacia delicatissimi? Ne sumo diceret mea, percipit repudiare eam no! Pro et lorem accommodare. At eius novum phaedrum mei? nIgnota conclusionemque mei no, eam ut munere fierent pertinacia. Ea enim insolens gloriatur duo, quis vituperatoribus pro no! Ei sed bonorum reprehendunt, aliquam nominavi his et. Magna decore referrentur id nec. Cum rebum ludus inimicus no, id cum iusto labores maluisset! Qui no omnis numquam apeirian, et vide interesset cum? Et nec nulla signiferumque. Enim instructior eos ei, solum tollit phaedrum his in? No vix malorum ornatus, cu quo hinc everti iracundia, essent eruditi efficiendi ut nam. Altera saperet usu eu, errem expetenda cu duo. Has dolor splendide et, no mel cibo ancillae voluptatum, mutat antiopam deterruisset ei qui. Dolores scripserit concludaturque est id, ea animal facilisi splendide qui, quo at animal voluptua instructior.nMeis voluptatum eu eum',1);
INSERT INTO posts VALUES(13,'My First Posts','2022-02-03 13:00:07.296565',replace(replace('Mel nulla legimus senserit id. Vim purto tractatos in, te vix error regione, erant laudem legere an vel. Falli fierent ius ex! In legere iriure est, id vis prima maluisset, purto numquam inimicus ut eos! In duo antiopam salutatus, an vel quodsi virtute definitiones. Est te sumo voluptaria, ius no putant argumentum, alienum ocurreret vim cu? Volumus democritum no vel, virtute commune an est. Vel te propriae lobortis rationibus, no eum odio neglegentur? Duo an sumo ignota latine! Nec mazim aperiam percipitur eu, id his dicit omnium.\r\n','\r',char(13)),'\n',char(10)),2);
INSERT INTO posts VALUES(14,'Neque porro quisquam','2022-02-03 13:03:24.613742','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum iaculis ultrices commodo. Maecenas eu elementum turpis. Donec a orci sagittis, placerat tellus in, ultrices mauris. Nullam feugiat arcu ipsum, eu laoreet ipsum auctor vel. Ut at leo est. Duis pretium leo est, a efficitur dui faucibus ac. Nulla facilisis ligula id ullamcorper blandit. Donec vehicula lorem ac lectus condimentum, eget eleifend eros viverra. Pellentesque nec ex dolor. Nullam congue ut sapien non vulputate. Vivamus velit libero, ultrices in tortor sed, suscipit varius nibh. Mauris pharetra euismod rhoncus',2);
INSERT INTO posts VALUES(15,'Sit et novum omnes','2022-02-03 13:04:28.712225','Sed bibendum pharetra blandit. Vivamus in diam dolor. Proin mollis ac magna sed fringilla. Curabitur feugiat congue pulvinar. Aliquam erat volutpat. Curabitur nec elit molestie, mattis nisl eget, condimentum purus. Sed nec ligula vitae arcu tristique maximus. Proin facilisis ultrices risus at molestie. Maecenas porta, mauris eget bibendum viverra, tellus erat ultrices tellus, vitae placerat risus nisi a nibh. Donec tempor, ante sit amet convallis pulvinar, ex ante molestie enim, at ullamcorper sapien dolor eget mauris. Quisque et leo nec neque laoreet suscipit. Curabitur vestibulum odio nec lacinia scelerisque. Curabitur malesuada erat justo, sit amet tempor quam malesuada vel',2);
INSERT INTO posts VALUES(17,'In rhoncus','2022-02-03 13:05:21.180717','In rhoncus, nisi eu luctus consequat, est nisl dictum dolor, sed tempor augue massa ut mauris. Vestibulum turpis nibh, suscipit ac viverra vitae, interdum sed risus. Nulla in dui fermentum, egestas risus sed, consectetur arcu. Aliquam et odio id eros consequat ultrices. Sed commodo volutpat semper. Nam elit ligula, vehicula quis dapibus eget, pulvinar sit amet dolor. Praesent blandit efficitur dapibus.',2);
INSERT INTO posts VALUES(18,'Vivamus','2022-02-03 13:05:48.698762','Vivamus vel facilisis ante. Phasellus consequat risus pretium nibh ultrices viverra. Sed tempor ligula vel diam venenatis suscipit. Nulla et odio id massa aliquam tincidunt sit amet a diam. Pellentesque dignissim quis mauris non suscipit. Cras dolor lorem, bibendum et ante in, aliquam sagittis lorem. Aenean sagittis, arcu non iaculis eleifend, orci arcu pulvinar diam, tempor ultricies dui dolor ut risus. Proin ac risus ut metus euismod condimentum. Integer porttitor diam vitae tellus tincidunt, ac euismod ligula elementum. Sed eu mauris vitae erat porta placerat. Donec sed eros purus. Nam mollis, eros sit amet vehicula pretium, libero lectus elementum sem, eget tempus odio odio vitae ex. Aliquam id lobortis nisi, a malesuada velit. Curabitur iaculis purus ac orci vehicula, venenatis vehicula nibh pharetra. Nulla dictum pellentesque nunc eget ornare.',2);
INSERT INTO posts VALUES(19,'Proin sed erat ','2022-02-03 13:06:14.916020','Proin sed erat eu arcu pretium faucibus ac eu nunc. Integer non fringilla libero, eget fringilla sapien. Aenean varius purus sem, vel mattis nunc tincidunt ut. Sed feugiat, elit vel auctor sollicitudin, dolor ligula egestas massa, a sollicitudin dui odio porttitor nunc. Nullam quis ligula auctor, dapibus tellus vel, volutpat quam. Curabitur lacinia eros et elementum pulvinar. Morbi nisi tortor, porta in venenatis nec, luctus eu risus. Sed dui nisi, condimentum quis nulla sed, pretium tempor mauris. Ut lacinia orci at enim pretium, et pellentesque quam viverra. Ut mollis massa et sem tristique, non ullamcorper nisi tristique. Donec tincidunt finibus facilisis. Donec suscipit ex ac risus laoreet dapibus. Integer at sodales ex, vel blandit justo.',2);
INSERT INTO posts VALUES(20,'Aenean vitae','2022-02-03 13:06:38.106216','Aenean vitae mattis urna. Integer pretium dui sit amet purus commodo scelerisque. Suspendisse potenti. Donec pretium nibh blandit, pretium metus quis, laoreet ante. Praesent facilisis vehicula tortor, sed bibendum lectus tincidunt sit amet. Phasellus dignissim imperdiet odio, ac varius ante hendrerit ac. Proin ut felis in enim condimentum convallis dignissim ut ex. Donec eu eros quis nibh tempus lobortis sed ut quam. Ut ullamcorper odio eget erat vestibulum, vitae tristique massa viverra.',2);
INSERT INTO posts VALUES(21,'Etiam sed egesta','2022-02-03 13:06:59.864757','Etiam sed egestas ipsum, nec tincidunt arcu. Integer ac tristique ipsum. Nullam varius mi sed laoreet egestas. Cras at diam aliquam, facilisis ipsum sit amet, rutrum odio. Suspendisse in nibh sed sapien faucibus gravida. Morbi ornare lacus at elit malesuada, vitae molestie sem ullamcorper. Mauris quis justo ante. Nunc vitae lobortis arcu, ac accumsan justo. Donec pretium facilisis dolor, a ultricies risus blandit ac. Aliquam nec egestas mauris.',2);
INSERT INTO posts VALUES(22,'Donec semper magna ','2022-02-03 13:07:31.991236','Donec semper magna et justo volutpat maximus. Nam interdum ex quis orci pharetra aliquam. Nunc sodales laoreet scelerisque. Donec quis tortor a dui laoreet faucibus at sit amet mi. Vivamus pulvinar sed odio ut vestibulum. Phasellus fringilla sed lectus id suscipit. Ut dictum gravida fermentum. Donec ut lectus dolor. Duis eleifend erat in lectus dapibus dictum. Proin eu orci porta, tempus nisi id, efficitur augue. Aenean et lacinia leo, a accumsan justo. Mauris molestie elementum erat, ac rhoncus ex. Ut laoreet non odio eget faucibus. In malesuada turpis non velit varius, non tempus sapien egestas. Praesent sodales dolor nec pellentesque cursus.',2);
INSERT INTO posts VALUES(23,'Suspendisse ','2022-02-03 13:07:54.556164','Suspendisse potenti. Pellentesque cursus, dui nec imperdiet scelerisque, erat eros sollicitudin sapien, non posuere lectus justo vitae lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse in ligula posuere, rhoncus ipsum a, fermentum dolor. Vivamus nulla orci, semper ut velit ac, elementum condimentum lorem. Nam lobortis metus risus, eget facilisis dui maximus ut. Sed sem orci, tincidunt iaculis viverra eget, finibus nec justo. Nunc porta vel purus ac lacinia. Aenean finibus, odio a posuere viverra, nulla urna tincidunt ex, sagittis vestibulum nisl dolor posuere leo. Vestibulum metus orci, bibendum id eleifend quis, euismod ac velit. Integer scelerisque interdum malesuada.',2);
INSERT INTO posts VALUES(24,'My First Posts','2022-02-03 13:09:42.359113','Hello there, I''m a backend developer using Python and there are mainly two Python backend frameworks for web development. Django and Flask. You can pick up any one of them and use the framework for web development.',1);
INSERT INTO posts VALUES(25,'Flask application','2022-02-03 13:11:05.329714',replace(replace('\r\nFlask is a micro web framework of Python. It is so-called because it does not need particular tools or libraries. It is a very simple framework and you can learn it very easily compared to Django.\r\nI used Flask to create this blog and I hope you like it.\r\n','\r',char(13)),'\n',char(10)),1);
INSERT INTO posts VALUES(26,'Learning Programming','2022-02-03 13:11:39.571912','Quo inani quando ea, mel an vide adversarium suscipiantur. Et dicunt eleifend splendide pro. Nibh animal dolorem vim ex, nec te agam referrentur. Usu admodum ocurreret ne.Et dico audire cotidieque sed, cibo latine ut has, an case magna.',1);
INSERT INTO posts VALUES(27,'The Rise of Data Science','2022-02-03 13:12:11.128900','Per omittam placerat at. Eius aeque ei mei. Usu ex partiendo salutandi. Pro illud placerat molestiae ex, habeo vidisse voluptatum cu vel, efficiendi accommodare eum ea! Ne has case minimum facilisis, pertinax efficiendi eu vel!Et movet semper assueverit his. Mei at liber vitae. Vix et periculis definiebas, vero falli.',1);
INSERT INTO posts VALUES(28,'5 Tips for Writing Catchy Headlines','2022-02-03 13:12:47.454678',replace(replace('Ea homero possit epicuri est, debitis docendi tacimates cu duo? Ad lorem cetero disputando pri, veniam eruditi tacimates per te.\r\n','\r',char(13)),'\n',char(10)),1);
INSERT INTO posts VALUES(29,'How To Create A YouTube Channel','2022-02-03 13:13:13.478189','Sit et novum omnes. Nec ea quas minim tractatos, usu in aperiam mentitum necessitatibus, ut omnis equidem moderatius quo. Eos ad putent aeterno praesent. Eos omnium similique id, his accommodare philosophia at. Causae lucilius similique in mea, ut regione tritani voluptatibus mel! At possim offendit eum, aeque denique prodesset pro te? At pro quem laudem. Et agam democritum eos? Ea quod probatus usu, no ferri fabulas cotidieque mei? Numquam nusquam quo in, quo et molestiae complectitur. Nihil semper ei qui. Modo omnes forensibus duo ex, te est diceret bonorum labores! Magna ponderum eos ea. Cu vim diceret mnesarchum, graeci periculis in vis. Est no iriure suavitate',1);
INSERT INTO posts VALUES(30,'Best Programmers Throughout History','2022-02-03 13:13:42.199865',replace(replace('Mel  nulla legimus senserit id. Vim purto tractatos in, te vix error regione, erant laudem legere an vel. Falli fierent ius ex! In legere iriure est, id vis prima maluisset, purto numquam inimicus ut eos! In duo antiopam salutatus, an vel quodsi virtute definitiones. Est te sumo voluptaria, ius no putant argumentum, alienum ocurreret vim cu? Volumus democritum no vel, virtute commune an est. Vel te propriae lobortis rationibus, no eum odio neglegentur? Duo an sumo ignota latine! Nec mazim aperiam percipitur id his dicit...\r\n','\r',char(13)),'\n',char(10)),1);

