version: '3'

services:
  mysql:
    container_name: mysql_container
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Myservername
      MYSQL_DATABASE: myapp
    cap_add:
      - SYS_NICE
    ports:
      - '8080:8080'

